services:
  - type: web
    name: goit-fastapi-app
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
  - type: static
    name: goit-fastapi-docs
    rootDir: ./docs
    buildCommand: "poetry run make html"
    publishPath: "build/html"
    pullRequestPreviewsEnabled: false
    autoDeploy: false