"""add_role_field_to_users

Revision ID: 1dd1225d8bbb
Revises: 490f9dd3810f
Create Date: 2025-09-08 12:46:39.546680

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "1dd1225d8bbb"
down_revision: Union[str, Sequence[str], None] = "490f9dd3810f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    user_role_enum = postgresql.ENUM("USER", "ADMIN", name="userrole")
    user_role_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            user_role_enum,
            nullable=False,
            server_default="USER",  # <-- Это решает проблему
        ),
    )
    # ### end Alembic commands ###
    op.alter_column("users", "role", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    user_role_enum = postgresql.ENUM("USER", "ADMIN", name="userrole")
    user_role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
