"""add refresh_token to users

Revision ID: 490f9dd3810f
Revises: 558e27d71976
Create Date: 2025-09-04 11:45:46.484972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "490f9dd3810f"
down_revision: Union[str, Sequence[str], None] = "558e27d71976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("refresh_token", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "refresh_token")
    # ### end Alembic commands ###
